// Personal details and links, in one place. Empty strings hide the matching
// button, so nothing ever links to a page that does not exist yet.
export const SITE = {
  name: "Jasper Pathuis",
  url: "https://jasper.hyphosting.com",
  email: "pathuisjasper@gmail.com",
  github: "https://github.com/jappie-p",
  /** the public repo of this site */
  repo: "https://github.com/jappie-p/portfolio",
  /** TODO Jasper: your LinkedIn URL (hidden while empty) */
  linkedin: "",
  /** CV per language, generated by scripts/cv-pdf.mjs from the /cv route */
  cv: { nl: "/cv/jasper-pathuis-cv-nl.pdf", en: "/cv/jasper-pathuis-cv-en.pdf" },
  region: { lat: 52.09, lon: 5.12 },
} as const;

/** The public base path (e.g. "/v3" on a sub-path deploy), for plain links to public/ files. */
export const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
